pipeline check 4

diff --git a/.github/workflows/smoke_test.yml b/.github/workflows/smoke_test.yml
--- a/.github/workflows/smoke_test.yml
+++ b/.github/workflows/smoke_test.yml
@@ -5,9 +5,55 @@ on:
     
 
 jobs:
-  test:
+  smoke:
     runs-on: ubuntu-latest
 
     steps:
-      - name : Echo Message
-        run: echo "Smoke Test successfully ✅"
+      - uses: aws-actions/configure-aws-credentials@v4
+        with:
+          role-to-assume: arn:aws:iam::508375325844:role/github-actions-deploy-role
+          aws-region: us-east-1
+      - name: Upload smoke_test.py on AWS
+        run: |
+            aws s3 cp smoke_test.py s3://508375325844-devops-scripts/smoke_test.py
+            --region us-east-1
+
+      - name: Smoke Test
+        id: smoke
+        run: |
+            CMD_ID=$(aws ssm send-command \
+            --targets "Key=tag:App,Values=flask" \
+            --document-name "AWS-RunShellScript" \
+            --parameters '{commands":[
+                "aws s3 cp s3://508375325844-devops-scripts/smoke_test.py /tmpr/smoke_test.py",
+                "python3 /tmpr/smoke_test.py",
+                "rm /tmpr/smoke_test.py"
+            ]}' \
+            --query "Command.CommandId" \
+            --output text 
+            --region us-east-1)
+
+            echo "cmd_id=$CMD_ID" >> "$GITHUB_OUTPUT"
+
+      - name: Show Results
+        run: |
+            sleep 20
+
+            aws ssm list-command-invocations \
+            --command-id "${{ steps.smoke.outputs.cmd_id }}" \
+            --details \
+            --region us-east-1 
+            --output text 
+
+            FAILED=$(aws ssm list-command-invocations \
+            --command-id "${{ steps.smoke.outputs.cmd_id }}" \
+            --query "length(CommandInvocations[?Status=='Failed'])" \
+            --output text \
+            --region us-east-1)
+
+            if [ "$FAILED" -gt 0 ]; then
+                echo "::error::Smoke Test Failed on $FAILED instances ❌"
+                exit 1
+            else
+                echo "Smoke Test Passed on all instances ✅"
+            fi
